### ISSUE TITLE
As an artist, I want to upload my art so I can promote my work

### ISSUE THREAD

**Issue by ges134** [CloeD/wannabe-deviant-art#5]
## Preconditions

- [ ] The artist should have an account on the system
- [ ] The artist should be connected 

## Additional notes

This only concerns the uploading of an artistic work or the creation of an entity.

## Tasks

- [ ] Create a uploading page
- [ ] Create a way to link the uploading page into the rest of the application
- [ ] Create a controller and service to manage the uploading action
- [ ] Make validation for the upload
- [ ] Save the entity

## Blocking issues

- [ ] #6
