### ISSUE TITLE
As an artist, I want to browse all artworks

### ISSUE THREAD

**Issue by ges134** [CloeD/wannabe-deviant-art#6]
## Preconditions

- [ ] The artist should have an account on the system
- [ ] The artist should be connected 

## Additional notes

A connected artist can browse all the artwork that is made available to the application. This does not include any type of filtering.

## Tasks

- [ ] Create an "all arts" page
- [ ] Make a service to fetch all arts.
- [ ] Make a pagination system in "all arts" page

## Blocking issues

_TBD._
