### ISSUE TITLE
As an artist, I want to browse my own art

### ISSUE THREAD

**Issue by ges134** [CloeD/wannabe-deviant-art#7]
## Preconditions

- [ ] The artist should have an account on the system
- [ ] The artist should be connected 

## Additional notes

This could act as a _my profile_ section of the application.

## Tasks

- [ ] Create a _my profile_ page
- [ ] Create a controller and service to manage the search by user.
- [ ] Make a pagination system

## Blocking issues

_TBD._
