### ISSUE TITLE
As an artist, I want to browse art by user or by keywords so that I can search for specific artwork

### ISSUE THREAD

**Issue by ges134** [CloeD/wannabe-deviant-art#8]
## Preconditions

- [ ] The artist should have an account on the system
- [ ] The artist should be connected 
- [ ] It can be possible to browse artwork

## Additional notes

A connected artist can browse all the artwork that is made available to the application. This does not include any type of filtering.

## Tasks

- [ ] Create a searchbar 
- [ ] Create a keywords section on the art upload page
- [ ] Create the service to search art based on keywords and users

## Blocking issues

- [ ] #6
